# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LodosUiProject/Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(800, 480)
        Form.setStyleSheet("#Form{\n"
"    background-image: url(:/res/main/bg.png);\n"
"}\n"
"\n"
"#saat{\n"
"    color: white;\n"
"}\n"
"\n"
"#warnText1, #warnText2{\n"
"    color: white;\n"
"}\n"
"\n"
"#warnText2{\n"
"    float: right;\n"
"}\n"
"\n"
"")
        self.korna = QtWidgets.QLabel(Form)
        self.korna.setGeometry(QtCore.QRect(380, 330, 32, 32))
        self.korna.setText("")
        self.korna.setPixmap(QtGui.QPixmap(":/res/main/horn.png"))
        self.korna.setObjectName("korna")
        self.far = QtWidgets.QLabel(Form)
        self.far.setGeometry(QtCore.QRect(260, 330, 42, 35))
        self.far.setText("")
        self.far.setPixmap(QtGui.QPixmap(":/res/main/far.png"))
        self.far.setObjectName("far")
        self.silecek = QtWidgets.QLabel(Form)
        self.silecek.setGeometry(QtCore.QRect(480, 330, 49, 35))
        self.silecek.setText("")
        self.silecek.setPixmap(QtGui.QPixmap(":/res/main/silecek.png"))
        self.silecek.setObjectName("silecek")
        self.signalWarning = QtWidgets.QLabel(Form)
        self.signalWarning.setGeometry(QtCore.QRect(5, 5, 86, 86))
        self.signalWarning.setText("")
        self.signalWarning.setPixmap(QtGui.QPixmap(":/res/main/signal.png"))
        self.signalWarning.setObjectName("signalWarning")
        self.leftBar = QtWidgets.QLabel(Form)
        self.leftBar.setGeometry(QtCore.QRect(30, 210, 176, 192))
        self.leftBar.setText("")
        self.leftBar.setPixmap(QtGui.QPixmap(":/res/main/Left_Bar.png"))
        self.leftBar.setObjectName("leftBar")
        self.rightBar = QtWidgets.QLabel(Form)
        self.rightBar.setGeometry(QtCore.QRect(580, 205, 183, 198))
        self.rightBar.setText("")
        self.rightBar.setPixmap(QtGui.QPixmap(":/res/main/Right_Bar.png"))
        self.rightBar.setObjectName("rightBar")
        self.mainBar = QtWidgets.QLabel(Form)
        self.mainBar.setGeometry(QtCore.QRect(290, 50, 221, 221))
        self.mainBar.setText("")
        self.mainBar.setPixmap(QtGui.QPixmap(":/res/main/Main_bar.png"))
        self.mainBar.setObjectName("mainBar")
        self.mainBar_2 = QtWidgets.QLabel(Form)
        self.mainBar_2.setGeometry(QtCore.QRect(360, 370, 67, 89))
        self.mainBar_2.setText("")
        self.mainBar_2.setPixmap(QtGui.QPixmap(":/res/main/lodos-50x50.png"))
        self.mainBar_2.setObjectName("mainBar_2")
        self.warning = QtWidgets.QLabel(Form)
        self.warning.setGeometry(QtCore.QRect(5, 442, 36, 32))
        self.warning.setText("")
        self.warning.setPixmap(QtGui.QPixmap(":/res/main/alert.png"))
        self.warning.setObjectName("warning")
        self.warning2 = QtWidgets.QLabel(Form)
        self.warning2.setGeometry(QtCore.QRect(755, 442, 36, 32))
        self.warning2.setText("")
        self.warning2.setPixmap(QtGui.QPixmap(":/res/main/alert.png"))
        self.warning2.setObjectName("warning2")
        self.saat = QtWidgets.QLabel(Form)
        self.saat.setGeometry(QtCore.QRect(710, 10, 91, 31))
        self.saat.setMinimumSize(QtCore.QSize(67, 17))
        font = QtGui.QFont()
        font.setFamily("URW Gothic [urw]")
        font.setPointSize(25)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.saat.setFont(font)
        self.saat.setObjectName("saat")
        self.warnText1 = QtWidgets.QLabel(Form)
        self.warnText1.setGeometry(QtCore.QRect(50, 445, 321, 31))
        self.warnText1.setMinimumSize(QtCore.QSize(67, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.warnText1.setFont(font)
        self.warnText1.setObjectName("warnText1")
        self.warnText2 = QtWidgets.QLabel(Form)
        self.warnText2.setGeometry(QtCore.QRect(430, 445, 321, 31))
        self.warnText2.setMinimumSize(QtCore.QSize(67, 17))
        font = QtGui.QFont()
        font.setFamily("Noto Sans CJK SC")
        font.setPointSize(17)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.warnText2.setFont(font)
        self.warnText2.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.warnText2.setObjectName("warnText2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saat.setText(_translate("Form", "00:00"))
        self.warnText1.setText(_translate("Form", "lorem ipsum dolor sit amet"))
        self.warnText2.setText(_translate("Form", "lorem ipsum dolor sit amet"))
import main_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
